apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudflare-ddns
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: mirioeggmann/cloudflare-ddns:latest
          restartPolicy: OnFailure
